---
id: 109413
name: "#26567検証用"
description: ''
user:
  id: 824
  email: eri.wheeler@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: bigquery
    bigquery_connection:
      id: 290
      name: BigQuery Service Account
    gcs_uri: gs://trocco-qa/test-by-eri/tmp-*
    gcs_uri_format: custom_path
    query: SELECT * FROM trocco_qa_data_check._benchmark_mockaroo
    location: US
    temp_dataset: test_by_eri
    cleanup_gcs_files: true
    use_legacy_sql: false
    cache: true
    file_format: CSV
    bigquery_job_wait_second: 600
    custom_variables: []
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns:
      - name: id
        type: long
      - name: bool
        type: boolean
      - name: long
        type: long
      - name: double
        type: double
      - name: string
        type: string
      - name: date
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %z"
      - name: timestamp
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %z"
      - name: timestamptz
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %z"
      - name: json_array
        type: json
      - name: email
        type: string
      - name: file_name
        type: string
      - name: base64_url
        type: string
      quote: "\""
      escape: "\""
    decoders:
    - type: gzip
  out:
    type: bigquery
    bigquery_connection:
      id: 290
      name: BigQuery Service Account
    dataset: test_by_eri
    table: Testing26567
    auto_create_dataset: false
    mode: replace
    location: US
    open_timeout_sec: 300
    timeout_sec: 300
    send_timeout_sec: 300
    read_timeout_sec: 300
    retries: 5
    allow_quoted_newlines: true
    column_options: []
    template_table: ''
    time_partitioning:
      type:
      field:
      expiration_ms:
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: long
    - name: bool
      src: bool
      default: ''
      type: boolean
    - name: long
      src: long
      default: ''
      type: long
    - name: double
      src: double
      default: ''
      type: double
    - name: string
      src: string
      default: ''
      type: string
    - name: date
      src: date
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %z"
    - name: timestamp
      src: timestamp
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %z"
    - name: timestamptz
      src: timestamptz
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %z"
    - name: json_array
      src: json_array
      default: ''
      type: json
    - name: email
      src: email
      default: ''
      type: string
    - name: file_name
      src: file_name
      default: ''
      type: string
    - name: base64_url
      src: base64_url
      default: ''
      type: string
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
